doctype = "<!DOCTYPE html>"
headOpen = "<head>"
headClose = "</head>"
title = "CV | Ledda Bryan"
bodyOpen = "<head>"
bodyClose = "</head>"
htmlOpen = '<html lang="en">'
htmlClose = "</html>"
name = "Bryan"
surname = "Ledda"
age = "27 ans"
pro = "Dev"